FROM qmcgaw/ddns-updater
COPY ./config.json /updater/data/
# RUN chown -R 1000 /updater/data
# RUN chmod 700 /updater/data
# RUN chmod 400 /updater/data/config.json

# sudo chown -R 1000 data
# # all access (for creating json database file data/updates.json)
#
# chmod 400 data/config.json
