version: "3.7"
services:

  consul-template:
    image: ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_PREFIX:-}dynamic-dns-consul-template:${DOCKER_TAG:-cache}
    build:
      context: ./consul-template

  refresh-certificates:
    image: ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_PREFIX:-}dynamic-dns-consul-template:${DOCKER_TAG:-cache}
    build:
      context: ./consul-template

  nginx:
    image: ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_PREFIX:-}dynamic-dns-nginx:${DOCKER_TAG:-cache}
    build:
      context: ./nginx
      args:
        PORT: "${TARGET_PORT:-443}"
